### PR TITLE
Update drivers.md

### PR DESCRIPTION
**Pull request by AnotherButler**
Replace with new section name to reflect new structure.

### CODE REVIEW

**Comment by AnotherButler** [comment]
@hugueskamba @rajkan01 When you get the chance, could one of you please review this to make sure the content is still accurate with these changes?

**Comment by AnotherButler** [comment]
@iriark01 This is waiting on engineering review. I changed things to match our new section name, but I need confirmation I didn't accidentally change the meaning of anything.

**Comment by iriark01** [comment]
@rajkan01 and @hugueskamba will one of you have time to look at this?

**Review by hugueskamba — COMMENTED** [review]
Why renaming drivers to I/0?
Are we referring to the `mbed-os/drivers` directory? Not all drivers are for I/O (e.g watchdog) and the directory is called `drivers` not `io`.
@bulislaw @evedon Can you please comment?

**Comment by iriark01** [comment]
From the restructure work we did, we learned:
* It's more intuitive to users.
* It's task-based, rather than code-based.
* Yes, we still have a devices directory in the code.
* If there are drivers that aren't I/O, you may need to move them elsewhere. No on had brought that up previously, but I could see that slipping through.

**Comment by evedon** [comment]
This page should be for drivers in general. If we need a specific page for I/O drivers then we should write a new one.

**Comment by iriark01** [comment]
In this structure, do you think it's worth splitting I/O and Drivers to two?
https://os.mbed.com/docs/mbed-os/development/introduction/index.html

**Comment by iriark01** [comment]
I've split the group into two: 
https://os.mbed.com/docs/mbed-os/development/apis/drivers.html
https://os.mbed.com/docs/mbed-os/development/apis/input-output-i-o.html
For the intro page, I think I need a bit of help. I currently have the same page twice, and for I/O it simply says "this is a subset of Drivers". Before I try rewriting the intro, I would like to know if there are parts of it that are only correct for I/O or that are never correct for it.

**Comment by iriark01** [comment]
@hugueskamba could you help me figure out what the intros should cover?
https://os.mbed.com/docs/mbed-os/development/apis/drivers.html
https://os.mbed.com/docs/mbed-os/development/apis/input-output-i-o.html

**Comment by hugueskamba** [comment]
> @hugueskamba could you help me figure out what the intros should cover?
> https://os.mbed.com/docs/mbed-os/development/apis/drivers.html
> https://os.mbed.com/docs/mbed-os/development/apis/input-output-i-o.html

Perhaps something similar to http://www.keil.com/pack/doc/CMSIS/Driver/html/index.html for the Drivers page.
Perhaps something similar to https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_IO/FreeRTOS_Plus_IO.html for the I/O page

**Comment by iriark01** [comment]
Rejecting the PR; I will work on intros for API categories when we have them all sorted out

**Pull request closed without merging**
