### PR TITLE
update rtos examples links

### PR DESCRIPTION
**Pull request by maciejbocianski**
examples move PR:
https://github.com/ARMmbed/mbed-os-examples-docs_only/pull/69

### CODE REVIEW

**Comment by maciejbocianski** [comment]
The error looks not related:

```
/main.cpp:38:44: error: no matching function for call to 'TLSSocket::connect(const char [12], int)'

./mbed-os/features/netsocket/TLSSocketWrapper.h:166:27: note: candidate: virtual nsapi_error_t TLSSocketWrapper::connect(const SocketAddress&)
```

**Review by AnotherButler — APPROVED** [review]
Thanks for the PR 👍

**Comment by maciejbocianski** [comment]
I moved all RTOS examples changes here

**Review by jamesbeyond — APPROVED** [review]
LGTM

**Comment by maciejbocianski** [comment]
@jamesbeyond @AnotherButler 
I think I fixed tls socket example 
https://github.com/ARMmbed/mbed-os-5-docs/pull/1246

**Comment by jamesbeyond** [comment]
snippets been merged

**Pull request merged**
