### PR TITLE
Update cli-reqs for python3

### PR DESCRIPTION
**Pull request by Patater**
Use python3 to avoid bugs like
https://github.com/ARMmbed/mbed-os/issues/12622 and
https://github.com/ARMmbed/mbed-os/issues/12848.

Internal-reference: https://jira.arm.com/browse/IOTBTOOL-672

### CODE REVIEW

**Comment by evedon** [comment]
Update looks good for python3 but the compiler info on the page is out-of-date.
(also PR should be against development branch)

**Comment by Patater** [comment]
> the compiler info on the page is out-of-date.

What needs updating with the compiler info?

**Comment by evedon** [comment]
This page looks really out-of-date. We should now recommend 
- Arm 6.13 https://jira.arm.com/browse/IOTCLOUDPR-3495
- GCC ARM 9-2019-q4-major 

we have removed ARM Compiler 5

**Comment by iriark01** [comment]
It is out of date. Please open your PR against `development` for the 6.0 release - `6.0.0-preview` is only for the alpha/beta releases and doesn't include any updates, only some additions like bare metal.

Also note there's an open PR about tools: https://github.com/ARMmbed/mbed-os-5-docs/pull/1290

**Comment by Patater** [comment]
Rebased on `development`.

**Review by iriark01 — APPROVED** [review]

**Pull request merged**
