### PR TITLE
Tools: Add search and replace script

### PR DESCRIPTION
**Pull request by hugueskamba**
Specify a search regex and replace regex in the configuration file.

```
usage: search_replace.py [-h] [--config CONFIG] [-v] path

Search for a pattern and replace it.

positional arguments:
  path             path to file or directory of files to look for the pattern
                   to replace. Only supports the following file extension:
                   ('md', 'txt')

optional arguments:
  -h, --help       show this help message and exit
  --config CONFIG  configuration file that has the pattern to search and what
                   to replace it with (default: ./search_replace.json)
  -v, --verbose    increase verbosity of status information. (default: False)
```

For https://jira.arm.com/browse/IOTCORE-1582

### CODE REVIEW

**Comment by iriark01** [comment]
Can you run it on a branch and show me the results? How does it run - only manually, right?

**Comment by hugueskamba** [comment]
> Can you run it on a branch and show me the results? How does it run - only manually, right?

You run it on a single file as follows:
```
hugkam01 at C02WD1BEHV2R in ~/projects/mbed/mbed-os-5-docs on hk_search_replace_demo [$]
$ python3 check_tools/search_replace.py docs/tools/testing/utest.md -v
```
The output is:
```
2020-05-12 11:20:05,616 - DEBUG - Starting script
2020-05-12 11:20:05,616 - DEBUG - Command line arguments:Namespace(config='/Users/hugkam01/projects/mbed/mbed-os-5-docs/check_tools/search_replace.json', func=<function search_replace at 0x101817158>, path='/Users/hugkam01/projects/mbed/mbed-os-5-docs/docs/tools/testing/utest.md', verbose=True)
2020-05-12 11:20:05,617 - DEBUG - Processing /Users/hugkam01/projects/mbed/mbed-os-5-docs/docs/tools/testing/utest.md...
```
You can view the result by looking at the diff as follows:
```
hugkam01 at C02WD1BEHV2R in ~/projects/mbed/mbed-os-5-docs on hk_search_replace_demo [!$]
$ git diff
diff --git a/docs/tools/testing/utest.md b/docs/tools/testing/utest.md
index f4d733007..a2d576678 100644
--- a/docs/tools/testing/utest.md
+++ b/docs/tools/testing/utest.md
@@ -23,7 +23,7 @@ The order of handler execution is:
 
 This example showcases functionality and proper integration with the [Greentea testing automation framework](greentea-testing-applications.html), while making use of the [unity test macros](https://github.com/ARMmbed/mbed-os/tree/master/features/frameworks/unity):
 
-[![View code](https://www.mbed.com/embed/?url=https://github.com/ARMmbed/mbed-os-examples-docs_only/blob/master/Tools_Testing/Utest_Ex_1/)](https://github.com/ARMmbed/mbed-os-examples-docs_only/blob/master/Tools_Testing/Utest_Ex_1/main.cpp)
+[![View code](https://www.mbed.com/embed/?url=https://github.com/ARMmbed/mbed-os-snippet-Utest_Ex_1/)](https://github.com/ARMmbed/mbed-os-snippet-Utest_Ex_1/main.cpp)
 
 
 Running this test will output the following:
```

To run on all files in a directory and all its sub-directories, specify the path of the directory as follows:
```
hugkam01 at C02WD1BEHV2R in ~/projects/mbed/mbed-os-5-docs on hk_search_replace_demo [!$]
$ pwd
/Users/hugkam01/projects/mbed/mbed-os-5-docs
hugkam01 at C02WD1BEHV2R in ~/projects/mbed/mbed-os-5-docs on hk_search_replace_demo [!$]
$ python3 check_tools/search_replace.py . -v
```
The output is:
```
2020-05-12 11:28:01,767 - DEBUG - Starting script
2020-05-12 11:28:01,767 - DEBUG - Command line arguments:Namespace(config='/Users/hugkam01/projects/mbed/mbed-os-5-docs/check_tools/search_replace.json', func=<function search_replace at 0x10b092158>, path='/Users/hugkam01/projects/mbed/mbed-os-5-docs/.', verbose=True)
2020-05-12 11:28:01,767 - DEBUG - Processing /Users/hugkam01/projects/mbed/mbed-os-5-docs/./redirects.json...
2020-05-12 11:28:01,767 - DEBUG - This file extension is not supported.
2020-05-12 11:28:01,767 - DEBUG - Processing /Users/hugkam01/projects/mbed/mbed-os-5-docs/./docs.json...
2020-05-12 11:28:01,767 - DEBUG - This file extension is not supported.
2020-05-12 11:28:01,768 - DEBUG - Processing /Users/hugkam01/projects/mbed/mbed-os-5-docs/./readme.md...
2020-05-12 11:28:01,769 - DEBUG - Processing /Users/hugkam01/projects/mbed/mbed-os-5-docs/./.travis.yml...
2020-05-12 11:28:01,769 - DEBUG - This file extension is not supported.
2020-05-12 11:28:01,770 - DEBUG - Processing /Users/hugkam01/projects/mbed/mbed-os-5-docs/./docs/bare_metal/using_bare_metal.md...
2020-05-12 11:28:01,770 - DEBUG - Processing /Users/hugkam01/projects/mbed/mbed-os-5-docs/./docs/bare_metal/mbed2_porting.md...
2020-05-12 11:28:01,771 - DEBUG - Processing /Users/hugkam01/projects/mbed/mbed-os-5-docs/./docs/bare_metal/c_small_libs.md...
2020-05-12 11:28:01,772 - DEBUG - Processing /Users/hugkam01/projects/mbed/mbed-os-5-docs/./docs/bare_metal/baremetal_example.md...
2020-05-12 11:28:01,773 - DEBUG - Processing /Users/hugkam01/projects/mbed/mbed-os-5-docs/./docs/bare_metal/bare_metal.md...
...
```

**Comment by iriark01** [comment]
I don't mind merging this but I'm not sure I'll run it!

**Comment by adbridge** [comment]
@iriark01 Uhhm shouldn't we have reviewed this first ?

**Comment by iriark01** [comment]
I must have misunderstood - I thought you had

**Pull request merged**
