### PR TITLE
Update contributing.md

### PR DESCRIPTION
**Pull request by AnotherButler**
Make changes from PR #64

Note: Please do NOT merge until someone who knows about contribution and legal confirms the link in line 105 is correct

### CODE REVIEW

**Comment by BlackstoneEngineering** [comment]
@jlovejoy is the best legal mind we have, and a layer to boot!

**Comment by jlovejoy** [comment]
you rang?  that link is actually wrong, as we now have SPDX v2.1 and we also added Appendix V which explains precisely how to use the SPDX license identifiers in source files.  I'm having trouble finding this file to make a direct edit and pull request though...

**Comment by jlovejoy** [comment]
just made new PR #110

**Comment by BlackstoneEngineering** [comment]
#awesome-laywering

**Comment by iriark01** [comment]
@AnotherButler I've merged PR 110 so there are merge conflicts now. Make sure to take all of @jlovejoy's edits into yours.

**Comment by AnotherButler** [comment]
@jlovejoy Thanks so much. That's awesome.

**Comment by AnotherButler** [comment]
@iriark01 Done

**Comment by iriark01** [comment]
I'm confused about the status now. Did we want to merge this, or close it because it was handled through another PR?

**Pull request closed without merging**
