### PR TITLE
feature-cmake-docs: add CMake docs structure

### PR DESCRIPTION
**Pull request by 0xc0170**
Build on top of #1428 . Only e2b6e57 relevant (or any subsequent commit if I fix reviews/add more)

This has nicer docs structure than one in 1428. This should be a good base for starting adding CMake docs

@rajkan01 @hugueskamba

### CODE REVIEW

**Comment by 0xc0170** [comment]
This is the build-system structure proposed here: https://github.com/ARMmbed/mbed-os-5-docs/tree/e2b6e57f76e0c852b2992b621e602eec157abe67/docs/tools/mbed_cli_2/build-system

**Comment by 0xc0170** [comment]
> Build on top of #1428 . Only e2b6e57 relevant (or any subsequent commit if I fix reviews/add more)

Rebased. @rajkan01 Please review if this structure makes sense

**Review by rajkan01 — COMMENTED** [review]
@0xc0170 I have reviewed the docs structure for CMake , please share your thoughts on below structure for Cmake
```
mbed_clii_2/cmake_build_system
                    ├── build_system
                    │    ├── cmake.md
                    │    └── cmakelists.md
                    │    └── toolchains.md
                    ├── build_profiles
                    │    └── profiles.md
                    ├── testing
                    │    └── greentea_test.md
                    │    └── unittests.md
                    └── porting
                          └── build_system_migration.md
                          └── mbed_target_porting.md
```

**Comment by 0xc0170** [comment]
I was not certain if we create new folders or not. Initially I thought yes, maybe we should. The current layout is to have testing.md and sections there to cover greentea test, unittests or any other test.

build-system could be the top level folder. Then we can have cmake, testing, porting folders. For both build systems.

**Comment by 0xc0170** [comment]
The layout without folders might follow what docs look like these days and might not be the best look (scrolling down between sections to find yours) ?

**Review by rajkan01 — APPROVED** [review]
LGTM

**Comment by 0xc0170** [comment]
@rajkan01 you can take any of the CMake added here, I'll keep cleaning up the python build tools today/tomorrow

**Pull request merged**
