### PR TITLE
Create utest.md

### PR DESCRIPTION
**Pull request by AnotherButler**
Add relevant page to handbook

### CODE REVIEW

**Comment by iriark01** [comment]
This is worth a minor edit. Also, should link to Greentea on docs site, not GitHub. Although we have a serious issue with the docs for Greentea being about as old as I am.

**Comment by AnotherButler** [comment]
@iriark01 Where do I find the Greentea docs?

**Comment by iriark01** [comment]
This is a good place to start https://github.com/ARMmbed/greentea/tree/master/docs
Brian D was talking to Anna and Azim about updating them. Feel free to nudge him.

**Comment by iriark01** [comment]
So do we need this?

**Comment by AnotherButler** [comment]
I was waiting to merge until we had Greentea docs on the docs site, so I could link to them instead of GitHub.

**Comment by iriark01** [comment]
Oh, good idea

**Comment by AnotherButler** [comment]
Closing in favor of #102

**Pull request closed without merging**
