### PR TITLE
Add FPGA info to spi.md

### PR DESCRIPTION
**Pull request by AnotherButler**
Add content about running SPI tests on the FPGA.

### CODE REVIEW

**Comment by AnotherButler** [comment]
ping @mprse

**Review by mprse — APPROVED** [review]
Added information is correct, but in this document defined/undefined behavior sections and are stale...

Some modifications have been added while working on example driver implementations and tests:
https://github.com/ARMmbed/mbed-os/blob/feature-hal-spec-spi/docs/design-documents/hal/0000-spi-overhaul.md#defined-behaviours

**Comment by mprse** [comment]
@jamesbeyond ping

**Comment by AnotherButler** [comment]
Because the added documentation is correct, I'll merge this PR. Let's make any changes to existing text in another PR. As we make changes to the code, please put PRs up against this repo. This is the official published documentation repo. Duplicating content in other repositories leads to out-of-sync, out-of-date content.

**Pull request merged**
