### PR TITLE
GCC version 6 -> 9

### PR DESCRIPTION
**Pull request by kjbracey**
Documentation update corresponding to https://github.com/ARMmbed/mbed-os/pull/10618 - hoping to get that into 5.15.

Also updated URLs to developer.arm.com to follow redirections.

### CODE REVIEW

**Review by AnotherButler — APPROVED** [review]

**Review by 0xc0170 — APPROVED** [review]
Sti

**Comment by AnotherButler** [comment]
@kjbracey-arm Did I mess this up when I tried to fix the merge conflict?

**Comment by kjbracey** [comment]
Yes, merge resolution went wrong - fixed it and rebased.

**Comment by 0xc0170** [comment]
> Sti

Not certain what went wrong with my latest review but I left the wrong comment, sorry about that. I've just noticed while reviewing the latest update.

**Comment by AnotherButler** [comment]
@kjbracey-arm Sorry about that. Thanks for the fix 👍

**Comment by kjbracey** [comment]
Adjusted to match new intended version.

**Review by 0xc0170 — APPROVED** [review]

**Comment by AnotherButler** [comment]
Closing in favor of #1174

**Pull request closed without merging**
