### PR TITLE
update tls socket example to latests APIs

### PR DESCRIPTION
**Pull request by maciejbocianski**
Fix CI example build error

### CODE REVIEW

**Comment by maciejbocianski** [comment]
@jamesbeyond please assign reviewers

**Review by 0xc0170 — APPROVED** [review]
👍

**Comment by AnotherButler** [comment]
Is this ready to merge, or are we waiting on further reviews?

**Comment by AnotherButler** [comment]
Actually, as this has one approval and should fix the failing tests, I'm going to merge. Please raise a new PR if there are issues.

**Pull request merged**
