### PR TITLE
Deprecate Wait.md

### PR DESCRIPTION
**Pull request by AnotherButler**
Replace content with deprecation warning.

### CODE REVIEW

**Review by bulislaw — CHANGES_REQUESTED** [review]
Not all calls were deprecated.

**Comment by AnotherButler** [comment]
So should we keep the body content and add a note that says "**Warning:** The `wait` and `wait_ms` calls of this API have been deprecated. In their place, please use [explicit sleep functions](../apis/power-management-sleep.html) and `wait_us`."?

**Comment by AnotherButler** [comment]
ping @bulislaw

**Review by bulislaw — COMMENTED** [review]
I think we should basically say the same as the deprecation notice (maybe with links): ```MBED_DEPRECATED_SINCE("mbed-os-5.14",
                      "'wait' is deprecated in favor of explicit sleep functions. To sleep, 'wait' should be replaced by "
                      "'ThisThread::sleep_for' (C++) or 'thread_sleep_for' (C). If you wish to wait (without sleeping), call "
                      "'wait_us'. 'wait_us' is safe to call from ISR context.")```

I'll update the examples not to use deprecated calls.

**Comment by AnotherButler** [comment]
@bulislaw Does this resolve your concerns?

**Review by bulislaw — APPROVED** [review]

**Pull request merged**
