### PR TITLE
Clarify spec version in psa_attestation.md

### PR DESCRIPTION
**Pull request by AnotherButler**
Clarify version to resolve issue #1217

### CODE REVIEW

**Review by adrianlshaw — APPROVED** [review]
Thanks @AnotherButler!

**Comment by adrianlshaw** [comment]
Actually, to keep it consistent with the styling of the other PSA pages (such as the mbed crypto page) it'd be preferable to describe the version a note, like the following

`Note: The version of PSA Attestation shipping with Mbed OS implements PSA Attestation API v1.0beta0.`

**Comment by AnotherButler** [comment]
ping @Patater

**Comment by Patater** [comment]
@AnotherButler Do we not want to follow Adrian's suggestion?

**Comment by AnotherButler** [comment]
> @AnotherButler Do we not want to follow Adrian's suggestion?

I thought I'd made that change. Good catch 👍

**Review by Patater — APPROVED** [review]

**Pull request merged**
