### PR TITLE
Update exporters.md

### PR DESCRIPTION
**Pull request by AnotherButler**
Fix code formatting

### CODE REVIEW

**Comment by iriark01** [comment]
The diff shows just an added blank line. What did I miss?

**Comment by AnotherButler** [comment]
On the docs site, all of the text below the ``` is included in the code formatting. Adding the blank line looks like it fixes that.

**Comment by iriark01** [comment]
Ah, awesome

**Comment by AnotherButler** [comment]
Yay to @theotherjimmy, who pointed it out to me.

**Pull request merged**
