### PR TITLE
Clarification - thread-safe and interrupt-safe

### PR DESCRIPTION
**Pull request by noutram**
Added a figure to help clarify the relationship between thread-safe and interrupt-safe as defined in this document.

Updated the title to reflect that this document also contains discussions on interrupt-safety.

Clarified the drivers section to hopefully help prevent some misunderstandings about the terminology

### CODE REVIEW

**Comment by noutram** [comment]
Great. Now I've been through the process once, I'll try and contribute a bit more often (I use these docs in my teaching).

**Comment by AnotherButler** [comment]
Awesome :) We appreciate the contributions.

**Comment by AnotherButler** [comment]
CC @0xc0170 Is this ready to merge?

**Comment by AnotherButler** [comment]
@theotherjimmy I forgot @0xc0170 was out. Is this ready to merge?

**Comment by theotherjimmy** [comment]
@AnotherButler I don't think it's waiting on anything. Feel free to merge.

**Pull request merged**
