### PR TITLE
Remove Arm Compiler 5 from style.md

### PR DESCRIPTION
**Pull request by AnotherButler**
Remove Arm Compiler 5 requirement.

### CODE REVIEW

**Comment by AnotherButler** [comment]
@kjbracey-arm @bulislaw Should this requirement be removed now?

**Review by bulislaw — CHANGES_REQUESTED** [review]
We need to replace it with 6. Also @kjbracey-arm can you update the C/C++ standards below to match your recent changes?

**Comment by kjbracey** [comment]
Yes, next bit should be

    - Uses the GNU11 standard for C.
    - Uses the GNU++14 standard for C++.

But that's assuming we *are* outright dropping the "must compile for ARM Compiler 5" . If that remains, ARM C 5 selects GNU99/GNU++11, and its "GNU++11" is only a subset (about 70% of language additions, no library).

I'm currently still uncertain whether I'm okay to push something to master that will not work in ARM C 5's C++11 subset. Changing these docs would give me permission, so that's a higher-level-than-me decision. Personally, I'm in favour.

**Comment by AnotherButler** [comment]
@bulislaw Is this OK to merge, or should we talk about this in person?

**Review by bulislaw — APPROVED** [review]

**Pull request merged**
