### PR TITLE
Updated ethernet and wifi interface description 

### PR DESCRIPTION
**Pull request by mikaleppanen**
This is ready for review.

### CODE REVIEW

**Comment by mikaleppanen** [comment]
@SeppoTakalo Could you check if these changes look valid?

**Comment by SeppoTakalo** [comment]
What does "wait to merge" label mean?

How long does this need to wait? In case I need to modify same files, I need to pick this same change to my PR in order to avoid conflicts.

**Comment by SeppoTakalo** [comment]
@mikaleppanen Please remove the "work in progress" label, as discussed.

@AnotherButler This is now complete and follow up work will be done in #470

**Comment by mikaleppanen** [comment]
Removed the work in progress.

**Comment by AnotherButler** [comment]
Please review my changes and resolve merge conflicts.

**Comment by mikaleppanen** [comment]
Resolved merge conflicts.

**Comment by AnotherButler** [comment]
@mikaleppanen Is it OK to make these changes to the live 5.8 docs, too? There's no content that only applies to 5.9, right?

**Comment by mikaleppanen** [comment]
@AnotherButler Yes, it is ok. These changes are valid also to 5.8.

**Pull request merged**
