### PR TITLE
Updated doxygen options in docs.json

### PR DESCRIPTION
**Pull request by SenRamakri**
Sync-up doxygen_options.json changes from mbed-os repo to Handbook repo.

### CODE REVIEW

**Comment by AnotherButler** [comment]
I believe features/filesystem has been taken off the excluded list.

**Comment by SenRamakri** [comment]
@pan- I'm trying to sync-up the doxygen_options.json from Handbook repo. If you think the changes are not good for BLE documentation we have to update that in Handbook repo as well. What paths/targets are missing?

**Comment by pan-** [comment]
@SenRamakri https://github.com/ARMmbed/Handbook/commit/99818b2b21e7a1e116a32cd8b82d54c1af52e859 removed `FEATURE_` from docs.json the 25th of september; this change was not reflected to `doxyfile_options.json` in mbed repository. 

@AnotherButler Could you indicate if  https://github.com/ARMmbed/Handbook/commit/99818b2b21e7a1e116a32cd8b82d54c1af52e859 should be reflected in mbed repository ?

**Comment by AnotherButler** [comment]
The two should be the same, and the handbook should match the mbed-os one, not the other way around. I thought @kegilbert put in a PR to mbed-os so that features/filesystem (not FEATURES) would no longer be excluded.

**Comment by kegilbert** [comment]
https://github.com/ARMmbed/mbed-os/pull/5395

Should cover it, not sure if we need a manual rebuild of docs to pull in those changes.

**Comment by AnotherButler** [comment]
I believe this has been superseded by https://github.com/ARMmbed/Handbook/pull/332

@SenRamakri Is it OK to close this in favor of 332?

**Comment by SenRamakri** [comment]
@AnotherButler , I think yes, But can you please add the PROJECT_NAME as below.
"PROJECT_NAME": "Mbed OS Reference",

**Pull request closed without merging**
