### PR TITLE
Create cli_install.md

### PR DESCRIPTION
**Pull request by AnotherButler**
- Move page to Handbook
- Include copy edits, mostly for active voice, consistent capitalization and inclusion of articles.

### CODE REVIEW

**Comment by arekzaluski** [comment]
@AnotherButler  Unfortunately I do not have rights to add a commit to this PR. It needs to include the latest changes in https://github.com/ARMmbed/mbed-cli-windows-installer/blob/master/setup.md. The changes can be found here: https://github.com/ARMmbed/mbed-cli-windows-installer/commit/d4b721871d1f43bbfaa5a288355df426d6f3aff1
@MarceloSalazar It may be a good idea to name it an alpha version. (It will be the first officially released version). What do you think about it?

**Comment by arekzaluski** [comment]
@JoeTheGuitarist ^

**Comment by JoeTheGuitarist** [comment]
It's not really an alpha - I think just stick with the versioning @arekzaluski has established without a readiness indicator like "alpha".

**Comment by AnotherButler** [comment]
@arekzaluski I didn't think there'd be permissions issues. My apologies. I have fixed it now. Thanks for the helpful link. :) 

Please let me know whenever this is ready for merging.

**Comment by JoeTheGuitarist** [comment]
Ready for merging now as far as I know. Thanks for your help @AnotherButler :)

**Pull request merged**
