### PR TITLE
Update outdated LoRaWAN tutorial

### PR DESCRIPTION
**Pull request by laurensslats**
The [current documentation](https://os.mbed.com/docs/mbed-os/v6.10/apis/LoRa-tutorial.html) references the old The Things Network environment with will go offline later this year. 

This PR updates the tutorial to reflect the new environment.

### CODE REVIEW

**Review by 0xc0170 — APPROVED** [review]

**Review by 0xc0170 — APPROVED** [review]

**Comment by laurensslats** [comment]
Thanks for approving @0xc0170. Hope this update can get merged shortly.

**Comment by laurensslats** [comment]
@0xc0170 any ideas on when this could be merged?

**Comment by 0xc0170** [comment]
I'll ask @donatieng to review & merge now

**Review by donatieng — APPROVED** [review]
LGTM!

**Comment by donatieng** [comment]
Thanks @laurensslats

**Pull request merged**
