### PR TITLE
Update note in mbed_targets.md

### PR DESCRIPTION
**Pull request by AnotherButler**
Update note to include method to force ArmC5.

### CODE REVIEW

**Review by SenRamakri — CHANGES_REQUESTED** [review]
@AnotherButler - I'm not sure we have to split that into 2 pages. This makes it harder to find. Now we have 2 ways of doing same thing explained in 2 pages. And also we eventually have to remove this and individual modifications to these section in separate pages makes it harder. I would prefer this to go in the same place as other doc and but its ok to make it shorter as you recommended without losing the main message that we will be deprecating ARMC5 in future.

**Comment by theotherjimmy** [comment]
@SenRamakri This does the same thing, but it's for different users. In particular `mbed_app.json` modification is for an application developer. This is for someone porting a target. I would not expect them to look in the same location for this information.

**Comment by SenRamakri** [comment]
@theotherjimmy - Although in general that is the case, I don't think anyone porting new targets should use AC5. Also compiler documentation will be applicable to both porting and app development not just app development.

**Comment by theotherjimmy** [comment]
> I don't think anyone porting new targets should use AC5.

The this should not be documented.

**Comment by theotherjimmy** [comment]
> Also compiler documentation will be applicable to both porting and app development not just app development.

This is documentation about `targets.json` which only applies to porting. Application developers should not be encouraged to modify Mbed OS.

**Review by theotherjimmy — APPROVED** [review]

**Comment by SenRamakri** [comment]
I think there is some confusion, it was never meant to be a "porting" related doc, its only meant to document how to use AC5. But yes, it does refer targets.json which is one way of doing it.

**Comment by theotherjimmy** [comment]
@SenRamakri @AnotherButler We could instead place this in the toolchain section, so long as this advice is clearly marked as "For porting a target that cannot use ArmC6 at this time". That way Application developer are not presented with an option that encourages modification of Mbed OS, as they're not doing target porting. (from offline discussion)

**Comment by theotherjimmy** [comment]
Part of the confusion is that when `targets.json` gets involved, it's immediately about target porting.

**Comment by SenRamakri** [comment]
@AnotherButler - I'll make the changes to the PR as @theotherjimmy suggested and push to other PR. Thanks for the quick review @theotherjimmy and @AnotherButler.

**Comment by SenRamakri** [comment]
@AnotherButler - Please close this PR as I have modifications to the other PR as we discussed.

**Pull request closed without merging**
