### PR TITLE
Verify that "id"s are unique in Travis CI

### PR DESCRIPTION
**Pull request by theotherjimmy**
You need to turn on Travis CI integration to make this run

Special character soup!

### CODE REVIEW

**Review by AnotherButler — APPROVED** [review]

**Comment by AnotherButler** [comment]
@iriark01 

@theotherjimmy wrote a script for us that will check all unique heading IDs any time a PR goes in to make sure that we don't duplicate them. He says it will only take about a minute to run. He can also do it for the Cloud docs if you like it.

**Comment by iriark01** [comment]
How far up do they need to be unique? @micque01 can headers repeat across books?

**Comment by theotherjimmy** [comment]
For what it's worth, this checks for duplicate ids in this repository at the moment.

**Comment by micque01** [comment]
I think it is fine if a header/id is repeated in a different book. I would try to avoid duplicating it in the same book though

**Pull request closed without merging**
