### PR TITLE
Removed PR template from docs

### PR DESCRIPTION
**Pull request by cmonr**
We have this: https://github.com/ARMmbed/mbed-os/blob/master/.github/pull_request_template.md

Do we a duplicate in the docs that then also needs to be maintained?

(For reference, this was brought up by @mrcoulter45 when creating https://github.com/ARMmbed/mbed-os/pull/9895#issue-257229865)

### CODE REVIEW

**Comment by adbridge** [comment]
IF this repo wants to use any of our scripts properly then it will need to keep the template....

**Comment by 0xc0170** [comment]
The intention was to show an example of good pull request . However it's hard to keep up to date if we improve (=change) things. We have this covered in how to create PR, should be sufficient.

Fine to be removed.

**Comment by AnotherButler** [comment]
I like not duplicating content that could get out of sync, but not being able to use scripts sounds concerning.

**Comment by AnotherButler** [comment]
@0xc0170 @adbridge Could y'all please confirm whether this will affect scripts?

**Comment by adbridge** [comment]
> 
> 
> IF this repo wants to use any of our scripts properly then it will need to keep the template....

The key is this, you don't have to have the template as long as people raise the PRs using the format that is in the template. That format is essential for the scripts. So it is up to you whether you lead people by giving the template automatically, or continually check that people have raised their PRs using the right format. Personally I still think your template is the best option, people rarely read guidelines properly....

**Review by AnotherButler — APPROVED** [review]

**Pull request merged**
