### PR TITLE
Update third_party.md

### PR DESCRIPTION
**Pull request by AnotherButler**
Fix bullet spacing

### CODE REVIEW

**Comment by iriark01** [comment]
Did you replace the four spaces with tab? Not sure that will work correctly on the docs site (despite working correctly on GitHub)

**Comment by AnotherButler** [comment]
No. I deleted extra spaces because on the docs site, all of the bullets are aligned, but some of them should be sub-bullets.

**Comment by iriark01** [comment]
I don't know why this keeps breaking. It was correctly sub-bulleted with four spaces the last time I looked at it, and now it's not despite (apparently) not being changed. I'll build this version and we'll see if that works.

**Comment by iriark01** [comment]
That doesn't seem to have fixed the issue

**Comment by AnotherButler** [comment]
You are correct. I will play with this.

**Pull request merged**
