### PR TITLE
RF driver porting guide refactored

### PR DESCRIPTION
**Pull request by JarkkoPaso**

### CODE REVIEW

**Comment by JarkkoPaso** [comment]
@artokin @mikter @juhhei01 please review. Link: https://github.com/ARMmbed/mbed-os-5-docs/blob/rf_porting_guide_update/docs/porting/connectivity/MeshInterface.md

**Review by juhhei01 — APPROVED** [review]

**Comment by juhhei01** [comment]
@JarkkoPaso https://github.com/ARMmbed/mbed-os-5-docs/pull/1045/commits/2eca2f89525e4f243651e57cdd51663c655083c3 How much we have collision with your work?

**Comment by juhhei01** [comment]
OK I checked your changes was done top of mine ones so no collision then.

**Comment by 0Grit** [comment]
@aglass0fmilk

**Comment by artokin** [comment]
This documentation has been moved to PR https://github.com/ARMmbed/mbed-os-5-docs/pull/1045

**Pull request merged**
