### PR TITLE
Correct callback size

### PR DESCRIPTION
**Pull request by gpsimenos**
This updates the example numbers to reflect a callback size of 4, as @evedon points out here https://github.com/ARMmbed/mbed-os-5-docs/pull/1199#discussion_r413818942.

### CODE REVIEW

**Review by ashok-rao — APPROVED** [review]
LGTM..

**Comment by iriark01** [comment]
Are we waiting for Evelyne to approve?

**Comment by evedon** [comment]
> Are we waiting for Evelyne to approve?

Ashok's approval is good enough.

**Comment by iriark01** [comment]
@gpsimenos  can this join 6.0 as well, or just development (6.1)?

**Comment by iriark01** [comment]
Ashok says 6.0 as well; I'll cherry pick

**Pull request merged**
