### PR TITLE
Fix Socket API link by using same ID in the "title" field in docs.json

### PR DESCRIPTION
**Pull request by SeppoTakalo**
* Fix the render engine bug found in https://github.com/ARMmbed/Handbook/pull/497

@iriark01 @AnotherButler Please merge in, so Socket-API links will be fixed.

### CODE REVIEW

**Comment by AnotherButler** [comment]
I don't like changing the title to "Socket API". None of the other section in the navigation bar (side panel) have "API" in their names. I don't like the inconsistency.

**Comment by SeppoTakalo** [comment]
Changed so that all links are pointing to `network-socket.html` instead of `socket-api.html`

**Comment by SeppoTakalo** [comment]
And header is now unchanged.

**Comment by AnotherButler** [comment]
Awesome. Thanks @SeppoTakalo

**Pull request merged**
