### PR TITLE
Update eventflags.md

### PR DESCRIPTION
**Pull request by AnotherButler**
Move because folder name changed.

### CODE REVIEW

**Comment by AnotherButler** [comment]
@bulislaw I'm still trying to figure out the Doxy link. Once I do, I'll merge this if it looks good to you.

**Comment by bulislaw** [comment]
Sounds good 👍

**Comment by AnotherButler** [comment]
@bulislaw I think the reason the Doxy link isn't working is because we need to build the Doxy. Are you able to do this?

**Comment by bulislaw** [comment]
Uhm build doxy where? I don't think I have any powers in the Handbook/portal page.

**Comment by AnotherButler** [comment]
@bulislaw I've moved one paragraph up and added what should be the right link to the Doxy. Is this OK to merge?

**Comment by bulislaw** [comment]
I'm getting 404 https://docs.mbed.com/docs/mbed-os-api/en/mbed-os-5.6/api/classrtos_1_1EventFlags.html

But maybe it'll be live after the release is out?

**Comment by AnotherButler** [comment]
Yes, it should be live after the release is out.

**Comment by bulislaw** [comment]
Looks good then :)

**Pull request merged**
