### PR TITLE
Replace underscores with dashes in "device_managment"

### PR DESCRIPTION
**Pull request by 0Grit**
Build complains otherwise.

### CODE REVIEW

**Comment by 0Grit** [comment]
@dlfryar Dunno who should review.

**Comment by dlfryar-zz** [comment]
cc: @peknis01 @AnotherButler

**Comment by screamerbg** [comment]
@loverdeg-ep Thanks for this.

**Review by screamerbg — APPROVED** [review]
LGTM

**Review by AnotherButler — APPROVED** [review]
Thanks for the PR 👍

**Pull request merged**
