### PR TITLE
Add notes about newly added postbuild step for uvision exporter

### PR DESCRIPTION
**Pull request by bridadan**
**NOTE:** this feature isn't scheduled for release until 5.13.0.

This is the accompanying docs for the feature added by this (yet to be merged) PR: https://github.com/ARMmbed/mbed-os/pull/10021

### CODE REVIEW

**Review by theotherjimmy — APPROVED** [review]

**Comment by AnotherButler** [comment]
Please review my edits to make sure I didn't accidentally change the meaning of anything.

**Review by theotherjimmy — APPROVED** [review]

**Comment by bridadan** [comment]
Looks great, thanks!

**Comment by bridadan** [comment]
Quick question about how y'all do merging vs releasing. The corresponding Mbed OS feature was merged yesterday: https://github.com/ARMmbed/mbed-os/pull/10021

However, it won't be released until 5.13.0. Will this PR be merged now or will you wait until 5.13?

**Comment by pavanbathla** [comment]
The employee/s who signed up these notifications is no longer with the company.
Can you help me delete his account?

Andrew.petersman@arm.com<mailto:Andrew.petersman@arm.com>
Pavan.bathla@arm.com<mailto:Pavan.bathla@arm.com>

**Comment by bridadan** [comment]
Hi @pavanbathla, which accounts are you asking about? And what would you like to remove them from?

**Comment by pavanbathla** [comment]
This is sergio.gemo@arm.com<mailto:sergio.gemo@arm.com>

I need to have pavan.bathla@arm.com<mailto:pavan.bathla@arm.com> off the account please
I need to have Andrew.petersman@arm.com<mailto:Andrew.petersman@arm.com> off the account please

Neither is employed by ARM

**Comment by AnotherButler** [comment]
Typically, I prefer to wait to merge this. However, that's flexible if there's a pressing reason to merge it into development now.

**Comment by bridadan** [comment]
Nope! Just wanted to see if I should mark this as done in JIRA before or after the merge. But if y'all are happy with the changes and just want to wait then I'm good.

**Review by AnotherButler — APPROVED** [review]

**Pull request merged**
