### PR TITLE
Update CircleCI config for branch "v5.15"

### PR DESCRIPTION
**Pull request by micque01**
Pull latest config changes from https://github.com/ARMmbed/docs-ci-config.git

### CODE REVIEW

**Comment by micque01** [comment]
@AnotherButler @iriark01 The Travis tests are failing, I'm not sure what is causing this. Is this a blocker to getting these PRs merged?

**Comment by iriark01** [comment]
I think you can merge, since you only worked on CircleCI so it can't be this PR that broke it.

@jamesbeyond can you help me figure out why Travis is failing?

**Comment by jamesbeyond** [comment]
> I think you can merge, since you only worked on CircleCI so it can't be this PR that broke it.
> 
> @jamesbeyond can you help me figure out why Travis is failing?

Hi @iriark01 ,
The reason that travis is failing is because it checks out the latest mbed-os, instead of using 5.15 version of mbed-os:
https://github.com/ARMmbed/mbed-os-5-docs/blob/v5.15/.travis.yml#L26
some of the mbed-os API deprecations, the 5.15 version doc code snippets not compatible with  latest mbed-os any more. the solution would be adding `git checkout mbed-os-5.15 ` after that line

**Comment by iriark01** [comment]
Thank you @jamesbeyond . Is that something you can do, or do I need to get another team invovled?

**Comment by jamesbeyond** [comment]
> Thank you @jamesbeyond . Is that something you can do, or do I need to get another team invovled?

Maybe @micque01 could you make that fix in this PR ? it is failing at the moment, 

you just need to put
`git checkout mbed-os-5.15`
after
https://github.com/ARMmbed/mbed-os-5-docs/blob/v5.15/.travis.yml#L26

**Comment by micque01** [comment]
Hi @jamesbeyond, thank you for the suggestion for the fix. However I am reluctant to fix it here as it is outside the scope of this PR and the maintenance of these tests is not in the web team's remit. A similar fix also needs to be applied to other branches v5.11, v5.12, v5.13, and v5.14, as it seems it is broken there too.

Is there a team responsible for the maintenance of these tests?

**Comment by iriark01** [comment]
Merging, since Travis failure shouldn't impact CircleCI configs

**Pull request merged**
