### PR TITLE
OOB_5.12 Clarification regarding label directories

### PR DESCRIPTION
**Pull request by GuyWi**
This PR is related to a documentation enhancement requested by @alzix as part of https://github.com/ARMmbed/mbed-os-5-docs/pull/1018.

### CODE REVIEW

**Review by theotherjimmy — CHANGES_REQUESTED** [review]
This is incorrect. `target.extra_labels_add` is not a different configuration variable, and `target.extra_labels_remove` is also available.

Please document that you may use both add and remove to modify the `target.extra_labels` value in addition to directly setting it.

**Comment by GuyWi** [comment]
Thanks for your review and clarification, @theotherjimmy !
Please approve.

**Review by theotherjimmy — CHANGES_REQUESTED** [review]
The value `extra_labels_add` is not something a user can configure; and the `TARGET` labels are all built from a single configuration value. Same for features and components.

**Comment by GuyWi** [comment]
Thanks again!
I failed to modify that. 
Updated.

**Review by theotherjimmy — APPROVED** [review]

**Pull request merged**
