### PR TITLE
Update testing_intro.md

### PR DESCRIPTION
**Pull request by AnotherButler**
Add content from shared Word doc.

### CODE REVIEW

**Comment by JoeTheGuitarist** [comment]
Hi Amanda, that looks generally good. The only thing that I didn't parse first time when reading was the "verb test" line.

**Comment by AnotherButler** [comment]
You're right. That sentence can be confusing. Do you have any suggestions on how to fix it?

**Comment by JoeTheGuitarist** [comment]
How about either in italics or quotation marks? 

"has a verb _test_" or "has a verb "test""

**Comment by AnotherButler** [comment]
@JoeTheGuitarist Is this OK to merge?

**Comment by AnotherButler** [comment]
Closing in favor of #253 to avoid weird history due to merge conflicts.

**Pull request closed without merging**
