### PR TITLE
Update description of USBAudio wav audio player example

### PR DESCRIPTION
**Pull request by mprse**
SD card driver is now included as a component.

### CODE REVIEW

**Review by AnotherButler — APPROVED** [review]
Thanks for the PR 👍

**Comment by AnotherButler** [comment]
@mprse Could you please resolve the merge conflicts?

**Comment by mprse** [comment]
@AnotherButler Rebased.

**Comment by AnotherButler** [comment]
ping @jamesbeyond

**Review by jamesbeyond — APPROVED** [review]
LGTM

**Pull request merged**
