### PR TITLE
move code "Serial Communication" snippets to other repo

### PR DESCRIPTION
**Pull request by jamesbeyond**
move code "Serial Communication" snippets to other repo.
update the snippet links

### CODE REVIEW

**Review by AnotherButler — APPROVED** [review]
Thanks for the PR 👍

**Comment by AnotherButler** [comment]
Code dependency: https://github.com/ARMmbed/mbed-os-examples-docs_only/pull/108

**Comment by jamesbeyond** [comment]
code merged

**Comment by jamesbeyond** [comment]
Hi @AnotherButler, This PR fixed the docs repo CI testing issue. it is good to go now

**Pull request merged**
