### PR TITLE
Replace RawSerial references

### PR DESCRIPTION
**Pull request by hugueskamba**

### CODE REVIEW

**Review by AnotherButler — APPROVED** [review]
Thanks for the PR 👍

**Comment by AnotherButler** [comment]
Do you know why Travis is failing?

**Comment by hugueskamba** [comment]
> Do you know why Travis is failing?

@jamesbeyond can you please add a link to the Slack channel thread about the CI issue so its progress can be monitored?
Thank you

**Comment by jamesbeyond** [comment]
Hi @hugueskamba, I think your CI issue is fixed, https://github.com/ARMmbed/mbed-os-5-docs/pull/1246
you just need to rebase your PR to master

**Comment by hugueskamba** [comment]
@AnotherButler Can this be merged now?

**Comment by AnotherButler** [comment]
@hugueskamba I'm waiting on confirmation from product about whether we're completely removing docs for deprecated APIs or putting a deprecation notice on those docs for a few months before removing them.

**Pull request merged**
