### PR TITLE
IAR Floating Point 

### PR DESCRIPTION
**Pull request by sarahmarshy**
This is a known bug for exporters. This instructs users how to utilize FPU instructions and avoid IAR errors.

### CODE REVIEW

**Comment by sarahmarshy** [comment]
Just saw a message from @screamerbg  that we might not be supporting IAR in release. The duplicate filenames issue?

**Comment by iriark01** [comment]
@screamerbg or @sg- are we supporting IAR?

**Comment by sg-** [comment]
we are supporting but i don't think this is the place for point docs about exporting errata... but maybe it is? Exporters in general need a really good hard refactor and cleanup

**Comment by sarahmarshy** [comment]
@sg- where is a good place? It looks like there is a section [https://github.com/sarahmarshy/Handbook/blob/5fa80ca27f3aa510d39ec0379f8d5e4aefb4c7b4/docs/dev_tools/third_party.md](here) about third party tool specifics, and it documents individual known issues with each tool.

**Comment by sarahmarshy** [comment]
@sg- obviously, this issue should ideally be fixed in software, but I thought it might be good to document it somewhere in the meantime.

**Comment by sg-** [comment]
That is a fine place. Just need to get used to the change in workflow from just edit a file to PR and rebuild the docs 👍

**Comment by iriark01** [comment]
Then I shall accept and rebuild the docs :) Thank you both

**Comment by iriark01** [comment]
Added to 5.1

**Pull request closed without merging**
