### PR TITLE
Add NVStore example content to Handbook

### PR DESCRIPTION
**Pull request by AnotherButler**
Add requested content from the NVStore example to the Handbook.

### CODE REVIEW

**Comment by dannybenor** [comment]
@davidsaada I think Ashok is right. Can you double check? The issue is because I copied from NVStore documentation

**Comment by davidsaada** [comment]
> I think Ashok is right. Can you double check? The issue is because I copied from NVStore documentation

Indeed he's right.

**Comment by AnotherButler** [comment]
If I change "mbed_lib.json" to "mbed_app.json", will this fix the problem?

**Comment by ashok-rao** [comment]
Thanks @dannybenor and @davidsaada for the confirmation.
@AnotherButler : Yes, please change the _lib.json to _app.json. Rest all LGTM!

**Pull request merged**
