### PR TITLE
Relax us ticker frequency requirement.

### PR DESCRIPTION
**Pull request by mprse**
This change is required by the Samsung S111(S5JS100). On this board timer clock used for us ticker operates at 26MHz.
According to current requirements, 8 MHz is the top limit for us ticker timer.

This change relaxes top limit to 100 MHz, but only for 32-bit timers.

### CODE REVIEW

**Review by AnotherButler — APPROVED** [review]
Thanks for the PR 👍

**Comment by AnotherButler** [comment]
Who should review this from engineering? @jamesbeyond ?

**Comment by AnotherButler** [comment]
@0xc0170 Who should review this from engineering?

**Comment by AnotherButler** [comment]
ping @0xc0170

**Comment by AnotherButler** [comment]
ping @jamesbeyond @0xc0170

**Review by jamesbeyond — APPROVED** [review]
Thank alot, this look good

**Pull request merged**
