### PR TITLE
fix typo in astyle command line options

### PR DESCRIPTION
**Pull request by lfdebrux**
Just a minor thing, I tried the suggested astyle command line options and got an error

I changed `--indents-switches` to `--indent-switches` and it worked

### CODE REVIEW

**Comment by 0xc0170** [comment]
Hi, what version of astyle are you running?

We are working on updating astyle, see please https://github.com/ARMmbed/Handbook/pull/400 (work in progress). this will actually also fix this (we will update astyle to 3.1 to get the latest fixes - after some time astyle was updated this year!)

**Comment by lfdebrux** [comment]
I'm running Artistic Style Version 2.05.1 from the Ubuntu repositories on Xenial

    $ apt-cache madison astyle
    astyle | 2.05.1-0ubuntu1 | http://gb.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages

**Comment by 0xc0170** [comment]
Thanks ,   this was a typo in the command (no matter what version do you use).

**Comment by AnotherButler** [comment]
@lfdebrux Great eye. Thanks for the PR.

**Pull request merged**
