### PR TITLE
Add initial version of PSA Initial Attestation Service

### PR DESCRIPTION
**Pull request by moranpeker**
PSA Initial Attestation Service documents

### CODE REVIEW

**Comment by AnotherButler** [comment]
Has the code for this merged onto master? If not, please provide a link to the relevant code PR in the comments, so we know when it merges.

**Comment by AnotherButler** [comment]
We require engineering review for all new/changed content, so I'm tagging @avolinski for content review.
If he's busy or someone else would be a better fit for this review, please tag a different engineer (who didn't write the PR).

**Comment by AnotherButler** [comment]
Our [porting template](https://github.com/ARMmbed/documentation_docs/blob/master/Docs/Templates/mbed-os-port-template.md) follows the basic structure of:

- description
- defined and undefined behavior
- implementation
- testing

I understand that connectivity and security may deviate from this structure a bit, but could you please include as much of this content as possible? If it's already there and I'm missing, could you please reorganize it to make it more obvious what's what?

**Review by GuyWi — COMMENTED** [review]
Based on a conversation I had today with Amir Aloosh, this document is not a porting document. It should go together with the [The Mbed implementation of PSA](https://os.mbed.com/docs/mbed-os/v5.11/apis/psa-api.html) document. I will move it after I speak with @AnotherButler about this.

**Comment by AnotherButler** [comment]
As we're now working on this in PR #986 , I'm closing this PR.

**Pull request closed without merging**
