### PR TITLE
Update Workflow.png

### PR DESCRIPTION
**Pull request by adbridge**
Remove all references to checking CLA

### CODE REVIEW

**Review by 0xc0170 — APPROVED** [review]

**Comment by 0xc0170** [comment]
> 5.11

is this good destination branch? Just curious how this works (not development branch) ?

**Comment by AnotherButler** [comment]
Does this image have the same name as before?

**Comment by adbridge** [comment]
> 
> 
> Does this image have the same name as before?

Yes

**Comment by 0xc0170** [comment]
Ready for integration?

**Review by AnotherButler — APPROVED** [review]
Sorry about the delay - we've been testing some new functionalities with images, and I wanted to be sure they don't affect this.

**Pull request merged**
