### PR TITLE
Add CLI config option to enable color in console

### PR DESCRIPTION
**Pull request by MarceloSalazar**
@AnotherButler please review

### CODE REVIEW

**Comment by AnotherButler** [comment]
FYI @madchutney @mark-edgeworth

**Review by AnotherButler — APPROVED** [review]

**Review by bridadan — APPROVED** [review]

**Comment by AnotherButler** [comment]
To confirm, this is relevant for 5.12, right?

**Comment by bridadan** [comment]
Yep, this feature has been around for sometime I believe.

**Comment by AnotherButler** [comment]
Muchas gracias.

**Pull request merged**
