### PR TITLE
Compress docs images for web

### PR DESCRIPTION
**Pull request by th3james**
I ran the free tool [ImageOptim](https://imageoptim.com/mac) over all the images for the docs and managed to reduce the average size by 1/3rd. Should result in no loss of visual fidelity and while making the pages load a bit faster.

### CODE REVIEW

**Review by AnotherButler — COMMENTED** [review]
I like the sound of that 👍 
Do we also make these changes to 5.10?

**Review by AnotherButler — APPROVED** [review]

**Comment by AnotherButler** [comment]
@th3james Only the docs team merges PRs in this repo.

**Comment by th3james** [comment]
@AnotherButler I'm happy to write something up about using ImageOptim, and maybe about best practices for web images generally. Where would you like that to live? In the README?
I'm not seeing a merge conflict, but I've rebased my changes and pushed again

**Comment by AnotherButler** [comment]
@rik I believe this is in the context of the conversation you just had with @iriark01 . Do you know the status of this PR?

**Comment by rik** [comment]
I've done a commit directly on the branch with all the images optimised for this branch: https://github.com/ARMmbed/mbed-os-5-docs/commit/2005a6aff6160550b64b6046876fabe6589982dd.

So we can now close this as done.

**Pull request closed without merging**
