### PR TITLE
Update network socket APIs overview page

### PR DESCRIPTION
**Pull request by SeppoTakalo**
* Remove obsolete and outdated examples
* Add diagram from Technology page
* Explain the API a bit
* Extend the non-blocking section

### CODE REVIEW

**Comment by AnotherButler** [comment]
This feels more like a typical API page than an overview page. Is that what you're going for?

**Comment by SeppoTakalo** [comment]
It should feel like it.
UDPSocket and TCPSocket are both sharing similar behaviours. This should describe what is common for both so that we don't need to copy&paste the documentation.

So describing API behaviour here is on purpose.

Later on, I might even add more data here when it affects both of our socket types.

**Comment by SeppoTakalo** [comment]
@AnotherButler Dropped the example, as you suggested.

This is now good to go from my point of view.

**Comment by SeppoTakalo** [comment]
@AnotherButler Looks good. Thank you.

**Pull request merged**
