### PR TITLE
Create contributing_to_greentea

### PR DESCRIPTION
**Pull request by AnotherButler**
Query: Should we include this document in the Handbook? It's the only greentea doc besides the README.

### CODE REVIEW

**Comment by iriark01** [comment]
I'm honestly not sure. Who's working on greentea now, Brian?

**Comment by theotherjimmy** [comment]
@bridadan Could you comment?

**Comment by bridadan** [comment]
I wouldn't include this since the only people who I think will care about this are people who are already at GitHub. So I think it's fine to keep the contributing doc just in the GitHub repo.

**Comment by AnotherButler** [comment]
Awesome. Thanks, @bridadan

**Comment by iriark01** [comment]
Will people find it? What's the general status of Greentea docs (I'm out of the loop)?

**Comment by bridadan** [comment]
@iriark01 I think the general status of Greentea docs is overall ok as far as I'm concerned thanks to @AnotherButler. We consolidated and cleaned everything up earlier this year.

As far as finding the CONTRIBUTING doc, if they go to the GitHub repo where they would be doing the contributing then they should find it there. It may just be me, but I think the CONTRIBUTING doc is probably one of the least examined documents in a project 😄 It's good to have one to reference for sure though.

**Comment by iriark01** [comment]
We're assuming they'll know they can contribute and that there's a guide. Do we mention that anywhere?

**Comment by bridadan** [comment]
Not sure, I would think a link to GitHub repository would be plenty. Do we do something similar for the `mbed-os` repo?

**Comment by iriark01** [comment]
I think the mbed OS contribution guide is in the docs. If you add a short sentence to the Greentea docs directing people to your contribution guide that'll be enough.

**Comment by bridadan** [comment]
Ok, issue should be solved now since https://github.com/ARMmbed/greentea/pull/222 was merged!

**Comment by iriark01** [comment]
Cool, thanks

**Pull request closed without merging**
