### PR TITLE
Create online_comp_tablet.md

### PR DESCRIPTION
**Pull request by AnotherButler**
Create guide to Online Compiler on tablets from old Handbook and add images

### CODE REVIEW

**Comment by AnotherButler** [comment]
@screamerbg Could you please review this and let me know if any of the content is no longer accurate? I understand you're the person who would know.

**Comment by BlackstoneEngineering** [comment]
How old is this doc?

**Comment by AnotherButler** [comment]
@BlackstoneEngineering The original version was in the old Handbook and was supposed to make it into the new one but didn't. I've cleaned up what I can, but I need someone to look over the content for me and confirm it's still correct.

**Comment by AnotherButler** [comment]
@screamerbg Could you please review this content and let me know if it is still correct?

**Comment by AnotherButler** [comment]
@screamerbg Please let me know what I can do to get this merged. Is there someone else who should review it?

**Comment by AnotherButler** [comment]
Note: Pending review at a later date.

**Comment by AnotherButler** [comment]
I've created this as a JIRA task in the backlog, so I'm closing the PR.

**Pull request closed without merging**
