### PR TITLE
Fix Queue code snippet

### PR DESCRIPTION
**Pull request by mprse**
cc @AnotherButler

### CODE REVIEW

**Review by AnotherButler — APPROVED** [review]

**Comment by mprse** [comment]
@AnotherButler Do you maybe know why CI is failing? I can't see how CI failure is related to this change.

**Comment by AnotherButler** [comment]
@mprse A change in `mbed-os` without a corresponding docs PR caused tests to fail. They're now passing again.

**Comment by mprse** [comment]
@AnotherButler Thanks for helping with CI.

**Comment by AnotherButler** [comment]
ping @jamesbeyond

**Comment by AnotherButler** [comment]
ping @jamesbeyond

**Review by jamesbeyond — APPROVED** [review]

**Comment by jamesbeyond** [comment]
LGTM

**Pull request merged**
