### PR TITLE
Change default build profile to bare-metal

### PR DESCRIPTION
**Pull request by kegilbert**
# DO NOT MERGE
Pending example PR: https://github.com/ARMmbed/mbed-os-example-blinky/pull/163

______________________
Not to hold up this PR, but wanted to bring up an additional discussion thread while here. I was going to include it in this PR but am pending a few other things first. 

I'd like to take this opportunity to touch on https://jira.arm.com/browse/IOTDOCS-759. Blinky as it stands now is RTOS agnostic with the exception of Thread reporting. Using the RTOS (EventQueue specifically) however we can improve quite a bit on how we report the system stats. 

The general idea/quickstart flow could be:
1. Here's Blinky without an RTOS (BareMetal, no RTOS, smaller footprint and introduces BareMetal profiles as a concept. Also allows us to smoke test BM on Mbed OS PRs without Mbed OS modifications).
2. Oh, you want threads/RTOS? Remove this one line and rebuild.
3. Cool, you added the RTOS. What's next? Choose to move on and dive into Mbed OS headfirst, link to all tutorials/examples. Want us to give you walk you through developing an Mbed OS application? Here's something cool you can do by using EventQueue to cleanup your application and Main thread:
image

Pending talks with Anthony/webteam on how to actually handle file diffs on the docs site, will update when we hear back.

### CODE REVIEW

**Review by SenRamakri — APPROVED** [review]
Nice work, Thanks @kegilbert

**Review by AnotherButler — APPROVED** [review]
This is now grammatically accurate, but I'll wait on content consensus before merging.

**Comment by kegilbert** [comment]
Adding Do Not Merge title pending example merge.

**Comment by 0Grit** [comment]
Question for elsewhere, but RTOS implies event queue? 
What if I don't want threads but I want event queue?

**Comment by kegilbert** [comment]
@loverdeg-ep  Very good question that as I've learned recently has been a topic of confusion in the past. 

The event queue does **not** require the RTOS to function. I could swap the proposed order to go from bare-metal, to eventqueue (the does require adding `events` to your `mbed_app.json` if you are using bare-metal, see below):
```json
"requires": ["bare-metal", "events"],
```

**Comment by AnotherButler** [comment]
@kegilbert Shall I close this PR, or do you want to leave it up?

**Comment by kegilbert** [comment]
I'll go ahead and close it, doesn't look like we'll be going this route. I'll put up another PR if https://github.com/armmbed/mbed-os-example-baremetal-blinky looks OK as a replacement.

**Comment by SenRamakri** [comment]
@kegilbert- Thanks much for taking care of this and also volunteering to generate the bare-metal example.

**Pull request closed without merging**
