### PR TITLE
DeviceKey ROT user API

### PR DESCRIPTION
**Pull request by dannybenor**
Documentation for devicekey

### CODE REVIEW

**Comment by AnotherButler** [comment]
@dannybenor I've completed an initial copy edit of this document. Please review my changes to make sure I didn't accidentally change the meaning of anything. 

Also, is this document only for users of the API, or is any of the information in here for those porting the API? Is all of the content API-specific, or are there any general concepts (such as Root of Trust) that we should move to the section overview page?

**Comment by dannybenor** [comment]
Example is https://github.com/ARMmbed/mbed-os-example-devicekey

**Comment by dannybenor** [comment]
https://github.com/ARMmbed/mbed-os/pull/6642

**Comment by AnotherButler** [comment]
@adbridge Could you please help us make sure the example is added to the teams repo?

**Comment by ashok-rao** [comment]
@AnotherButler , could you please update the confluence page with the link to this doc once it's available? Thanks.

**Comment by AnotherButler** [comment]
I'll merge this for 5.9, but we need to add the example to teams.

**Comment by AnotherButler** [comment]
Note: I added the example with help from @geky

**Pull request merged**
